services:
  ui:
    build: ./xom-ui
    ports:
      - "5173:5173"
    volumes:
      - ./xom-ui:/app # For hot-reload in dev
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Enables file watching inside Docker
    command: ["npm", "run", "dev"]
  server:
    build: ./xom-server
    ports:
      - "5000:5000"
    volumes:
      - ./xom-server:/app # For hot-reload in dev
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Enables file watching inside Docker
    restart: unless-stopped